# References..
# https://github.com/hakase-labs/hikari/blob/master/.travis.yml
# https://github.com/cpp3ds/cpp3ds
# https://github.com/cpluspluscom/ChessPlusPlus
# http://stackoverflow.com/questions/4250624/ld-library-path-vs-library-path
# https://docs.travis-ci.com/user/migrating-from-legacy/

sudo: false

language: c++

script: 
    - echo $CXXFLAGS
    - echo $LD_LIBRARY_PATH
    - echo $LIBRARY_PATH
    - ls -R $HOME/build/ninjarope/build-sfml/lib
    - make

cache:
  apt: true
  directories:
    - "$HOME/.travis/cmake/build/install"
    #- "$HOME/build/ninjarope/sfml/include"
    #- "$HOME/build/ninjarope/build-sfml/lib"

# Update Travis' gcc and build sfml (as the new libsfml-dev provided by travis has issues)
before_install:
    - if [ "$CC"  == "gcc"     ]; then export CC=gcc-5; fi
    - if [ "$CXX" == "g++"     ]; then export CXX=g++-5; fi
    - if [ "$CC"  == "clang"   ]; then export CC=clang-3.8; fi
    - if [ "$CXX" == "clang++" ]; then export CXX=clang++-3.8; fi
    - pushd . && cd $HOME
    - git clone https://github.com/LB--/travis.git travis
    - source "./travis/update-cmake.sh"
    - popd
    - source "./build_sfml.sh"

install:
    - export CXXFLAGS=-I$HOME/build/ninjarope/sfml/include
    - export LD_LIBRARY_PATH=$HOME/build/ninjarope/build-sfml/lib:$LD_LIBRARY_PATH
    - export LIBRARY_PATH=$HOME/build/ninjarope/build-sfml/lib:$LIBRARY_PATH

matrix:
    include:
# uncomment to include building with clang
    #- os: linux
      #compiler: clang
      #addons:
        #apt:
          #sources:
            #- ubuntu-toolchain-r-test
            #- llvm-toolchain-precise
            #- llvm-toolchain-precise-3.7
          #packages:
            #- clang-3.8
            #- g++-5
            #- libglew-dev
            #- libsndfile1-dev
            #- libopenal-dev
            #- libfreetype6-dev
            #- libx11-xcb-dev
            #- udev
            #- libudev-dev
            #- libpthread-stubs0-dev
            #- cmake
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libglew-dev
            - libsndfile1-dev
            - libopenal-dev
            - libfreetype6-dev
            - libx11-xcb-dev
            - udev
            - libudev-dev
            - libpthread-stubs0-dev
            - cmake

branches:
    only:
        - master
        - dev
