sudo: false
language: cpp
script: 
    - make
compiler: gcc
before_install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsfml-dev
    - g++-4.8

branches:
    only:
        - master
